version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/webservice
    overwrite: true
hooks:
  # BeforeInstall:
  #   - location: scripts/install.sh
  #     timeout: 400

  # AfterInstall:
  #   - location: scripts/post_install.sh
  #     timeout: 200

  ApplicationStart:
    - location: scripts/run.sh
      timeout: 120
      runas:ec2-user
