version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/webservice
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStart:
    - location: scripts/run.sh
      timeout: 120
      runas: ec2-user
