name: CI

on:
  push:
    branches: [Assignment-4]
  #pull_request:
  #branches: [main]

  workflow_dispatch:

jobs:
  build:
    name: Packer Workflow
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: zip app.zip ./* -r

      - run: packer init packer.pkr.hcl
      - run: packer build packer.pkr.hcl
