name: CI

on:
  push:
    branches: [Assignment-4]
  #pull_request:
  #branches: [main]

  workflow_dispatch:

jobs:
  build:
    name: Packer Workflow
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: zip app.zip ./* -r
      - run: ls -al
      - run: pwd
      - name: Step 2 - Packer Init
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: packer.pkr.hcl
      - name: Step 3- Packer Build
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          target: packer.pkr.hcl
        env:
          PACKER_LOG: 1
