name: CI
on:
  push:
    branches: [Assignment-7]
  workflow_dispatch:

jobs:
  build:
    name: Packer_Workflow
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm install
          npm run build --if-present
          zip -r webservice.zip ./
          git archive -o webservice.zip HEAD
          mkdir artifacts
          zip -r csye6225-webapp-${{ github.sha }}.zip webservice.zip
          cp csye6225-webapp-${{ github.sha }}.zip artifacts/
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.USER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.USER_SECRET_KEY }}
          aws-region: us-east-1
      - name: Copy artifacts
        run: |
          rm -rf aws
          aws deploy push 
          --application-name csye6225webapp 
          --description "Latest revision for csye6225-webapp-${{ github.sha }}" 
          --ignore-hidden-files 
          --s3-location s3://aws-codedeploy-dev-sonali/csye6225-webapp-${{ github.sha}}.zip 
          --source .
      - name: Call Code Deploy
        run: |
          aws deploy create-deployment 
          --application-name csye6225webapp 
          --deployment-config-name CodeDeployDefault.AllAtOnce 
          --deployment-group-name csye6225webappdeployment 
          --file-exists-behavior OVERWRITE 
          --s3-location bucket=s3://aws-codedeploy-dev-sonali,key=csye6225-webapp-${{ github.sha }}.zip,bundleType=zip
      - name: Packer Started
        run: |
          packer init packer.pkr.hcl
          packer validate -var-file="var.pkrvars.hcl" packer.pkr.hcl
          packer build -var-file="var.pkrvars.hcl" packer.pkr.hcl
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
