name: CI
on:
  push:
    branches: [Assignment-7]
  workflow_dispatch:

jobs:
  build:
    name: Packer_Workflow
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: zip -r webservice.zip ./
      - name: Packer Started
        run: |
          packer init packer.pkr.hcl
          packer validate -var-file="var.pkrvars.hcl" packer.pkr.hcl
          packer build -var-file="var.pkrvars.hcl" packer.pkr.hcl
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "AKIA256ELQTI7LUQZPID"
          aws-secret-access-key: "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"
          aws-region: us-east-1
      - name: Upload Zip to S3
        run: |
          rm -rf aws
          aws --region us-east-1 deploy push --application-name csye6225-webapp --description "Latest revision for csye6225-webapp-${{ github.sha }}" --ignore-hidden-files --s3-location s3://aws-codedeploy-dev-sonali/csye6225-webapp-${{ github.sha }}.zip --source .
