name: CI
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: PullRequest_Workflow
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-
      - run: zip -r webservice.zip ./
      - run: ls -al
      - name: Packer Started
        run: |
          packer init packer.pkr.hcl
          packer validate -var-file="var.pkrvars.hcl" packer.pkr.hcl
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
